apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvn014
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /nfs/cluster/data/pv/pvn014
    server: 192.168.1.99
