apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvn005
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /nfs/cluster/data/pv/pvn005
    server: 192.168.1.99
