apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.service.type: nodeport
    creationTimestamp: null
    labels:
      io.kompose.service: rabbitmq
    name: rabbitmq
  spec:
    ports:
    - name: "4369"
      port: 4369
      targetPort: 4369
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "25672"
      port: 25672
      targetPort: 25672
    - name: "15672"
      port: 15672
      targetPort: 15672
    selector:
      io.kompose.service: rabbitmq
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.service.type: nodeport
    creationTimestamp: null
    name: rabbitmq
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: rabbitmq
      spec:
        containers:
        - image: arm32v7/rabbitmq:latest
          name: rabbitmq
          ports:
          - containerPort: 4369
          - containerPort: 5672
          - containerPort: 25672
          - containerPort: 15672
          resources: {}
          volumeMounts:
          - mountPath: /bitnami/rabbitmq
            name: rabbitmq-rabbitmq-data
        restartPolicy: Always
        volumes:
        - name: rabbitmq-rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-rabbitmq-data
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: rabbitmq-rabbitmq-data
    name: rabbitmq-rabbitmq-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
kind: List
metadata: {}

