apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.service.type: nodeport
    creationTimestamp: null
    labels:
      io.kompose.service: redis
    name: redis
  spec:
    ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
    selector:
      io.kompose.service: redis
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.service.type: nodeport
    creationTimestamp: null
    name: redis
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: redis
      spec:
        securityContext:
          runAsUser: 1001
          fsGroup: 1001        
        containers:
        - image: arm32v7/redis:latest
          name: redis
          ports:
          - containerPort: 6379
          resources: {}
          volumeMounts:
          - mountPath: /data
            name: redis-redis-data
        restartPolicy: Always
        volumes:
        - name: redis-redis-data
          persistentVolumeClaim:
            claimName: redis-redis-data
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: redis-redis-data
    name: redis-redis-data
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 100Mi
  status: {}
kind: List
metadata: {}
